name: pytradeshifts
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy
  - pip
  - matplotlib
  - pandas
  - pytest
  - country_converter
  - networkx
  - geopandas
  - seaborn
  


