name: pytradeshifts
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy=1.26.2
  - scipy=1.11.4
  - matplotlib=3.8.2
  - pandas=2.1.3
  - pytest=7.4.3
  - jupyter=1.0.0
  - country_converter=1.2
  - networkx=3.2.1
  - geopandas=0.14.2
  - seaborn=0.13.1
  - geopy=2.4.1
